name: Build and Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        run: |
          
          # Authenticate with the container registry
          docker login --username bjornarron -p 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

          # Tag the Docker image
          docker tag docker tag image-id ghcr.io/bjornarron/flask:latest

          # Push the Docker image to the container registry
          docker push ghcr.io/bjornarron/flask:latest
