name: Build and Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/bjornarron/flask-example:latest .
          docker login ghcr.io --username bjornarron --password ${{ secrets.PAT_DEVOPS }}
          # Push the Docker image to the container registry
          docker push ghcr.io/bjornarron/flask-example:latest
  deploy:
    runs-on: deployment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy docker image for flask on VM
        run: |
            docker login ghcr.io --username bjornarron --password ${{ secrets.PAT_DEVOPS }}
            docker run ghcr.io/bjornarron/flask-example:latest -p 5000:5000


