name: Build and Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/bjornarron/flask:latest .
          # Push the Docker image to the container registry
          docker push ghcr.io/bjornarron/flask:latest
