name: Build and Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/bjornarron/flask-example:latest .
          docker login ghcr.io --username bjornarron -p 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
          # Push the Docker image to the container registry
          docker push ghcr.io/bjornarron/flask-example:latest
